---
name: Bundle-Simo
version: 0.0201
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: 'A bundle to install L<Simo> related modules [DISCOURAGED]'
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  Bundle::Simo:
    file: lib/Bundle/Simo.pm
    version: 0.0201
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
